# Generated by Django 3.1.2 on 2020-11-09 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(max_length=15, unique=True)),
                ('status', models.CharField(choices=[('option', 'Option'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=255)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('updatedby', models.CharField(max_length=255)),
                ('agencyname', models.CharField(max_length=255)),
                ('agencyid', models.PositiveIntegerField()),
                ('bookingtype', models.CharField(choices=[('account', 'Account'), ('creditcard', 'Creditcard')], default='', max_length=10)),
                ('shipcode', models.CharField(max_length=5)),
                ('shipname', models.CharField(max_length=100)),
                ('cruisecode', models.CharField(max_length=5)),
                ('cruisename', models.CharField(max_length=255)),
                ('cruiseembarkation', models.DateField()),
                ('cruiseduration', models.PositiveSmallIntegerField(max_length=3)),
                ('cruiseitinerary', models.JSONField()),
                ('ratecode', models.CharField(max_length=5)),
                ('ratename', models.CharField(max_length=255)),
                ('ratepricing', models.JSONField()),
                ('cabincode', models.CharField(max_length=5)),
                ('cabinname', models.CharField(max_length=100)),
                ('cancellationpolicy', models.JSONField()),
                ('currency', models.CharField(max_length=3)),
                ('totalprice', models.DecimalField(decimal_places=3, max_digits=15)),
                ('paymentschedule', models.JSONField()),
                ('nextpaymentdue', models.DateField()),
                ('nextpaymentoutstanding', models.DecimalField(decimal_places=3, max_digits=15)),
                ('transactions', models.JSONField()),
                ('totalpaid', models.DecimalField(decimal_places=3, max_digits=15)),
                ('leadtitle', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms'), ('Mstr', 'Mstr')], max_length=5)),
                ('leadgivenname', models.CharField(max_length=100)),
                ('leadlastname', models.CharField(max_length=100)),
                ('leademail', models.EmailField(max_length=255)),
                ('leadphone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadpassenger', models.BooleanField(default=False)),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms'), ('Mstr', 'Mstr')], max_length=5)),
                ('givenname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('dateofbirth', models.DateField(choices=[('adult', 'Adult'), ('child', 'Child'), ('infant', 'Infant'), ('senior', 'Senior')], max_length=10)),
                ('ageontravel', models.PositiveSmallIntegerField(max_length=3)),
                ('nationality', models.CharField(max_length=2)),
                ('language', models.CharField(max_length=7)),
                ('address', models.JSONField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=2)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('request', models.TextField()),
                ('documentation', models.JSONField()),
                ('pricing', models.JSONField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservation.reservation')),
            ],
        ),
    ]
