# Generated by Django 3.1.2 on 2020-11-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='ageontravel',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='cruiseduration',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
