# Generated by Django 3.1.2 on 2020-11-09 15:32

from django.db import migrations, models
import django.db.models.deletion
import io


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AvailableStatus', models.CharField(choices=[('AvailableStatus', 'AvailableStatus'), ('open', 'open'), ('booked', 'booked'), ('hold', 'hold'), ('grouphold', 'grouphold'), ('released', 'released')], max_length=20, verbose_name='AvailableStatus')),
                ('status', models.CharField(choices=[('AvailableStatus', 'AvailableStatus'), ('open', 'open'), ('booked', 'booked'), ('hold', 'hold'), ('grouphold', 'grouphold'), ('released', 'released')], default=io.open, max_length=15)),
                ('holdtime', models.DateTimeField(auto_now_add=True)),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.cabin')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.grade')),
                ('sailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.sailings')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField()),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.grade')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.rate')),
                ('sailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.sailings')),
            ],
        ),
    ]
