# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-02 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lms',
            old_name='from_date',
            new_name='FromDate',
        ),
        migrations.RenameField(
            model_name='lms',
            old_name='to_date',
            new_name='ToDate',
        ),
        migrations.AlterField(
            model_name='lms',
            name='working_days',
            field=models.IntegerField(),
        ),
    ]
