# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-02 13:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_auto_20170402_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lms',
            name='FromDate',
        ),
        migrations.RemoveField(
            model_name='lms',
            name='ToDate',
        ),
        migrations.AddField(
            model_name='lms',
            name='from_date',
            field=models.DateField(default=datetime.datetime(2017, 4, 16, 18, 55, 29, 743000), verbose_name='From_Date'),
        ),
        migrations.AddField(
            model_name='lms',
            name='to_date',
            field=models.DateField(default=datetime.datetime(2017, 4, 17, 18, 55, 29, 743000), verbose_name='To_Date'),
        ),
    ]
