# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-06 09:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_auto_20170406_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lms',
            name='from_date',
            field=models.DateField(default=datetime.datetime(2017, 4, 20, 15, 14, 2, 317000), verbose_name='From_Date'),
        ),
        migrations.AlterField(
            model_name='lms',
            name='to_date',
            field=models.DateField(default=datetime.datetime(2017, 4, 21, 15, 14, 2, 317000), verbose_name='To_Date'),
        ),
    ]
