# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-06 10:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_auto_20170406_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lms',
            name='from_date',
            field=models.DateField(default=datetime.datetime(2017, 4, 20, 15, 47, 27, 698000), verbose_name='From_Date'),
        ),
        migrations.AlterField(
            model_name='lms',
            name='to_date',
            field=models.DateField(default=datetime.datetime(2017, 4, 21, 15, 47, 27, 698000), verbose_name='To_Date'),
        ),
        migrations.AlterField(
            model_name='lms',
            name='working_days',
            field=models.IntegerField(default=1),
        ),
    ]
