# Generated by Django 3.1.2 on 2020-11-09 15:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('adult', 'Adult'), ('child', 'Child'), ('infant', 'Infant'), ('senior', 'Senior')], max_length=15)),
                ('value', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('commissionlevel', models.DecimalField(decimal_places=2, default=-1, max_digits=5)),
                ('accounttype', models.CharField(choices=[('port', 'Port'), ('starboard', 'Starboard')], max_length=20)),
                ('creditlimit', models.DecimalField(decimal_places=3, max_digits=20)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bedconfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Cabinattribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=5)),
                ('guaranteedpriority', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cabinholdduration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours')], max_length=15)),
                ('value', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cancellationpolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('daysbeforedeparture', models.PositiveSmallIntegerField()),
                ('type', models.CharField(choices=[('fixedfee', 'Fixed Fee'), ('percentage', 'Percentage')], max_length=15)),
                ('value', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('availableto', models.CharField(choices=[('image', 'Image'), ('ship', 'Ship'), ('grade', 'Grade'), ('rate', 'Rate'), ('cabin', 'Cabin')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Consortia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Cruise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=5)),
                ('nights', models.PositiveSmallIntegerField()),
                ('seadays', models.PositiveSmallIntegerField()),
                ('descriptions', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Depositpolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('daysbeforedeparture', models.PositiveSmallIntegerField()),
                ('type', models.CharField(choices=[('perpersonperday', 'Per Person Per Day'), ('percentage', 'Percentage'), ('perday', 'Per Day'), ('fixed', 'Fixed Value')], max_length=15)),
                ('value', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Diningseating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=5)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('validfrom', models.DateField(default=datetime.date.today)),
                ('validto', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Diningtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=5)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('inside', 'Inside'), ('outside', 'Outside'), ('balcony', 'Balcony'), ('suite', 'Suite')], max_length=15)),
                ('cabinquantity', models.PositiveSmallIntegerField()),
                ('guaranteed', models.BooleanField(default=False)),
                ('validfrom', models.DateField(default=datetime.date.today)),
                ('validto', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Groupreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewdaysbeforedeparture', models.PositiveSmallIntegerField()),
                ('paymentdaysbeforedeparture', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=255)),
                ('mingradepercentage', models.PositiveSmallIntegerField()),
                ('maxgradepercentage', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Imagesize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=15)),
                ('width', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Optiontime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('hours', 'Hours'), ('days', 'Days')], max_length=15)),
                ('value', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=5)),
                ('latitude', models.CharField(max_length=10)),
                ('longitude', models.CharField(max_length=10)),
                ('tender', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=5)),
                ('currency', models.CharField(max_length=3)),
                ('validfrom', models.DateField(default=datetime.date.today)),
                ('validto', models.DateField()),
                ('commissionoverride', models.DecimalField(decimal_places=2, max_digits=5)),
                ('restriction', models.CharField(blank=True, choices=[('port', 'Port'), ('starboard', 'Starboard')], max_length=15)),
                ('descriptions', models.JSONField()),
                ('agency', models.ManyToManyField(blank=True, to='configuration.Agency')),
                ('cancellationpolicy', models.ManyToManyField(to='configuration.Cancellationpolicy')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.market')),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=5)),
                ('length', models.PositiveIntegerField()),
                ('size', models.PositiveIntegerField()),
                ('standardcapacity', models.PositiveIntegerField()),
                ('totalcapacity', models.PositiveIntegerField()),
                ('totalcabins', models.PositiveIntegerField()),
                ('descriptions', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Sailings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('gtfpercentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cruise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.cruise')),
            ],
        ),
        migrations.CreateModel(
            name='Ratepricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstpassengerprice', models.DecimalField(decimal_places=3, max_digits=20)),
                ('secondpassengerprice', models.DecimalField(decimal_places=3, max_digits=20)),
                ('thirdpassengerprice', models.DecimalField(decimal_places=3, max_digits=20)),
                ('fourthpassengerprice', models.DecimalField(decimal_places=3, max_digits=20)),
                ('fifthpassengerprice', models.DecimalField(decimal_places=3, max_digits=20)),
                ('singlesupplement', models.DecimalField(decimal_places=3, max_digits=20)),
                ('available', models.PositiveSmallIntegerField()),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.grade')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.rate')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagefile', models.ImageField(upload_to=None)),
                ('imagesize', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=15)),
                ('associatedtype', models.CharField(choices=[('cruise', 'Cruise'), ('ship', 'Ship'), ('cabin', 'Cabin')], max_length=15)),
                ('associatedid', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.category')),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.ship'),
        ),
        migrations.CreateModel(
            name='CruiseItinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField()),
                ('extradescription', models.TextField()),
                ('arrivetime', models.TimeField()),
                ('departtime', models.TimeField()),
                ('cruise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.cruise')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.port')),
            ],
        ),
        migrations.CreateModel(
            name='Cruisefeesandtaxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cruise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.cruise')),
            ],
        ),
        migrations.AddField(
            model_name='cruise',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.ship'),
        ),
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('number', models.CharField(max_length=5, unique=True)),
                ('position', models.CharField(choices=[('forward', 'Forward'), ('midship', 'Midship'), ('aft', 'Aft')], max_length=15)),
                ('location', models.CharField(choices=[('port', 'Port'), ('starboard', 'Starboard')], max_length=15)),
                ('attr', models.ManyToManyField(to='configuration.Cabinattribute')),
                ('bedconfig', models.ManyToManyField(to='configuration.Bedconfiguration')),
            ],
        ),
        migrations.AddField(
            model_name='agency',
            name='market',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='configuration.consortia'),
        ),
    ]
